const menus = [{
    title: 'Menu 1',
    soup: 'Minestrone',
    soupPrice: '2.95',
    salad: 'Greek Salad',
    saladPrice: '4.75',
    lightFare: 'Vegetable Biriyani',
    lightFarePrice: '4.95',
    entree: 'Breaded Chicken on a Bun',
    entreePrice: '5.95',
 
}, 
{
    title: 'Menu 2',
    soup: 'Red Lentil Dal',
    soupPrice: '2.95',
    salad: 'Julienne Salad',
    saladPrice: '4.95',
    lightFare: 'Madras Chicken Salad Wrap',
    lightFarePrice: '4.95',
    entree: 'Fish and Chips',
    entreePrice: '5.95',
}, 
{
    title: 'Menu 3',
    soup: 'Spicy Squash & Pumpkin',
    soupPrice: '2.95',
    salad: 'Mediterranean Salad',
    saladPrice: '4.95',
    lightFare: 'Ham & Cheese Panini',
    lightFarePrice: '4.95',
    entree: 'Butter Chicken with Rice Pilaf',
    entreePrice: '5.95',
}, 
{
    title: 'Menu 4',
    soup: 'Clam Chowder',
    soupPrice: '2.95',
    salad: 'Israeli Couscous & Feta Salad',
    saladPrice: '4.95',
    lightFare: 'Pulled Pork on a Bun',
    lightFarePrice: '4.95',
    entree: 'Matar Paneer & Basmati Rice',
    entreePrice: '5.95',
}, 
{
    title: 'Menu 5',
    soup: 'Tomato',
    soupPrice: '2.95',
    salad: 'Caesar Salad',
    saladPrice: '4.95',
    lightFare: 'Burger & Fries',
    lightFarePrice: '4.95',
    entree: 'Beef & Broccoli with Fried Rice',
    entreePrice: '5.95',
}

];